name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: docker-compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from app
  push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: mercuriaal/devops:latest