name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create env file
        run: |
          echo "${{ secrets.DOTENV }}" > .env
      - run: make test
  push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: mercuriaal/devops:latest
          file: Dockerfile.production